# This is a basic workflow to help you get started with Actions

name: Deploy Surge Website   
on: [push]   
jobs:
       build:                           
           runs-on: ubuntu-latest 
           name: Deploying to surge 
           steps:    
           - uses: actions/checkout@v2 
           - name: Install Node.js
             uses: actions/setup-node@v2-beta
             with: 
               node-version: 12 
           - name: Update
             run: npx browserslist --update-db 
           - uses: borales/actions-yarn@v2.0.0 # `yarn install`
             with:
               cmd: install 
           - uses: borales/actions-yarn@v2.0.0
             with:
              cmd: build # will run `yarn build` command
           - name: Install Surge
             run: npm install --global surge  
           - name: Run surge
             run: surge ./build myexpense_hi.surge.sh --token ${{ secrets.SURGE_TOKEN }}
